module.exports = {
    MULTIPOINT: 'MultiPoint',
    MULTILINE: 'MultiLineString',
    MULTIPOLYGON: 'MultiPolygon',
    QUERY_CT: `SELECT * FROM pam.shapes_comp_trtmts_geojson`,
    QUERY_PARTIAL_FUND: `SELECT * FROM pam.trtmts_funding`,
    QUERY_PARTIAL_PROJ: `SELECT * FROM pam.trtmts_projects`,
    FUNDING_FIELDS: [
        'fund_bia',
        'fund_blm',
        'fund_bor',
        'fund_epanmed',
        'fund_fema',
        'fund_nfwsnmdgf',
        'fund_nmassoc',
        'fund_nmfinance',
        'fund_nmdgf',
        'fund_nmfd',
        'fund_nmusfs',
        'fund_nmslo',
        'fund_nrcs',
        'fund_nrcsusfs',
        'fund_other',
        'fund_private',
        'fund_rockyelk',
        'fund_swcd',
        'fund_tnc',
        'fund_tribepueblo',
        'fund_usfs',
        'fund_usfsnmfd',
        'fund_wildturkey',
        'fund_ycc'
    ],
    MATCH_FUNDING_FIELDS: [
        'fund_bia_match',
        'fund_blm_match',
        'fund_bor_match',
        'fund_epanmed_match',
        'fund_fema_match',
        'fund_nfwsnmdgf_match',
        'fund_nmassoc_match',
        'fund_nmfinance_match',
        'fund_nmdgf_match',
        'fund_nmfd_match',
        'fund_nmusfs_match',
        'fund_nmslo_match',
        'fund_nrcs_match',
        'fund_nrcsusfs_match',
        'fund_other_match',
        'fund_private_match',
        'fund_rockyelk_match',
        'fund_swcd_match',
        'fund_tnc_match',
        'fund_tribepueblo_match',
        'fund_usfs_match',
        'fund_usfsnmfd_match',
        'fund_wildturkey_match',
        'fund_ycc_match'
    ],
}